### PR TITLE
Create CODE_OF_CONDUCT.md file.

### PR DESCRIPTION
**Pull request by jwdonahue**
Should be SOP for GitHub sites.

### CODE REVIEW

**Comment by Haacked** [comment]
I would love to have a COC at the org level. I'll have to ask my colleagues if that's in the works. Thanks for adding this!

**Comment by tbull** [comment]
Here is a much more useful variant of a Code of Conduct. Needs some editing in details, though.
https://github.com/domgetter/NCoC

**Comment by alphapapa** [comment]
Not a good idea.  This project is essentially a niche discussion forum for best practices and a way to gauge *very rough* consensus among those who choose to participate.  There is essentially no organization in the first place.  The idea of policing and enforcement in such a context is ludicrous and counter-productive.

The trend of instituting codes of conduct in every little GitHub repo is being used to usurp power and oust those with certain political views.  It should be resisted.

Keep politics out of the FOSS community.  Keep it technical.

**Comment by jwdonahue** [comment]
@alphapapa  FOSS?

**Comment by jwdonahue** [comment]
It may be possible that no one has ever been banned from this site, however unlikely.  If so, that's wonderful, but eventually somebody will come along and go one post too far and they will get themselves banned.  When that happens, it's good to have a policy to point to.  I would consider a "don't spam us" policy better than nothing at all.

**Comment by alphapapa** [comment]
There's no need for such a policy.  The repo owners can handle issues as they see fit.  Anyone who doesn't like how they handle them can fork the repo, and the community members (as it were; I don't think this project necessarily qualifies as one, since it merely produces recommendations) can choose which they prefer to participate in.

One of the biggest problems with the merged document is the responsibilities it requires of the repo owners.  They are required to police community members behaviors in public venues, to act on complaints, etc.  For a project of this scale and purpose, that's simply ridiculous.  Imagine if every repo on GitHub had a policy like this, and a person who contributed to a bunch of them did something unpopular.  Every repo owner would be self-obligated to "enforce" their rules against that person.  Surely they have better and more important things to do.  

It's simply unwise for the repo owners to enter into such public obligations on behalf of--who exactly?  Anyone and everyone who wanders in?  It makes no sense.  It creates a vulnerability in which the repo owners can be required to act on random complaints from random people, or else be accused of not enforcing their rules and therefore supporting whatever unpopular behavior the complainee (?) is accused of.

This project is entirely about how to organize software development.  Anything else is completely out of its scope.  Keep it technical.

**Comment by jwdonahue** [comment]
@alphapapa, given that the community is tech savvy, combined with the history I have personally read through on the issues and PR tabs here, I don't anticipate this will require much effort. 

@Haacked, thanks for the merge!

**Pull request merged**
