### PR TITLE
Improve readability of item 11

### PR DESCRIPTION
**Pull request by tomschr**
As discussed in #561, introduce a list to separate the different rules to make item 11 more accessible.

Keep in mind: **The wording was NOT CHANGED**! It's only **the layout** to make the whole paragraph more "digestible". :wink:

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
Closing & re-opening to trigger CI

**Comment by alexandrtovmach** [comment]
@tomschr Thanks for contribution 👍
Could you fix linter warnings?

**Comment by tomschr** [comment]
@alexandrtovmach Thanks for the hint. :+1: I've looked at the linter warnings. However, it seems to me, the linter is wrong. :wink: 

In the lines 135-141, the linter complains about "incorrect indentation before bullet". However, this is Markdown and that allows sub lists inside a parent list. Check the file and in my fork, it [is rendered correctly](https://github.com/tomschr/semver/blob/feature/561-item11/semver.md).

The mentioned list is a **sub list** of line 133. Removing those spaces would result in a semantically incorrect list.

I don't know this linter, I've never used it. Maybe I missed something. In that case I'm happy to include these fixes. However, it seems to me, this linter doesn't know or understand sub lists inside another parent sub list.

What should I do?

**Comment by alexandrtovmach** [comment]
@tomschr Just intend for two more spaces

**Comment by alexandrtovmach** [comment]
@tomschr I fixed that for you :+1:

**Comment by tomschr** [comment]
Thank you very much @alexandrtovmach ! :+1: :heart:

**Pull request merged**
