### PR TITLE
switch to plural first person pronoun

### PR DESCRIPTION
**Pull request by adamralph**
Since the product transitioned from single person to collaboration some time ago.

Note that the _About_ section still contains the following for posterity:

> The Semantic Versioning specification was originally authored by Tom Preston-Werner, inventor of Gravatar and cofounder of GitHub.

### CODE REVIEW

**Comment by adamralph** [comment]
any interest?

**Comment by adamralph** [comment]
tumbleweed

**Review by revolter — APPROVED** [review]

**Comment by Kully** [comment]
> any interest?

I think this is a good change. Your change is even semantics-related! 😄

**Review by alexandrtovmach — APPROVED** [review]
LGTM!

**Comment by alexandrtovmach** [comment]
Thanks for contribution, and sorry for delay :+1:

**Comment by adamralph** [comment]
@alexandrtovmach thanks for the merge.

Out of interest, how do these changes get propagated to https://semver.org/? Is there any documentation describing that?

**Comment by alexandrtovmach** [comment]
It'll be online tomorrow
we have a GitHub Action workflow which run every night to sync content between repos

**Comment by adamralph** [comment]
👍 thanks for the info @alexandrtovmach — here's a PR to answer that question in future — https://github.com/semver/semver/pull/735

**Pull request merged**
