### PR TITLE
explain how changes are published to the website

### PR DESCRIPTION
**Pull request by adamralph**
see https://github.com/semver/semver/pull/623#issuecomment-886478646

### CODE REVIEW

**Review by alexandrtovmach — APPROVED** [review]
thanks for adding this

**Comment by joo4849** [comment]
735

**Comment by joo4849** [comment]
/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/gm

**Comment by adamralph** [comment]
reported to GitHub

**Review by 294m — COMMENTED** [review]
Fatih Namlı Dürüm resturant

**Comment by adamralph** [comment]
Err... what is going on here? Has some bad actor gained write access to the repo?

**Comment by alexandrtovmach** [comment]
@adamralph already did

**Pull request merged**
