### PR TITLE
feat: Added linter and workflow; Fixed linter warnings

### PR DESCRIPTION
**Pull request by alexandrtovmach**
Added linter and workflow to validate markdown changes. Used the same list of rules as in [semver/semver.org](https://github.com/semver/semver.org)

### CODE REVIEW

**Comment by alexandrtovmach** [comment]
@indirect could you, if this PR looks okay, approve it, merge and then turn on rule to require passing workflow check for PRs to `master`

**Comment by alexandrtovmach** [comment]
@indirect Seems like rule for required CI is not enabled, could you double check?

**Comment by alexandrtovmach** [comment]
aaaand, in this repo no `/check` trigger, only CI linter

**Comment by indirect** [comment]
@alexandrtovmach oh that makes sense! oops 😅 unfortunately, it is not possible to require a check that has never run before, so we have to wait until after it runs:

image

**Pull request merged**
