### PR TITLE
Hyphen should be hyphens in the pre-release clause

### PR DESCRIPTION
**Pull request by jwdonahue**
Fix for #465 How many hypens are you allowed in the prerelease tag.

### CODE REVIEW

**Comment by jwdonahue** [comment]
Updated.

**Comment by r00ster91** [comment]
Can any maintainer approve this? I would like to clearly know if it's valid to use multiple hyphens or not.

**Comment by elduddz** [comment]
@r00ster91 the answer is yes, but agree the doc needs that clarification.

**Comment by jwdonahue** [comment]
@r00ster91, see the threads referenced in #460, regarding regex. It's long been well established that `---` is a valid prerelease tag consisting of two hyphens. It is unlikely that you will find anyone to argue otherwise.

**Comment by jwdonahue** [comment]
@anangaur, @dherman, @indirect, @isaacs, @segiddins, @steveklabnik, @Seldaek,

Do any of you have any objections to committing this trivial update?

**Pull request merged**
